# Generated by Django 5.1.7 on 2025-05-13 13:14

from django.db import migrations, models
import django.db.models.deletion

def migrate_teacher_data(apps, schema_editor):
    Student = apps.get_model('attendance', 'Student')
    for student in Student.objects.all():
        # Use primary_teacher as the new teacher
        student.teacher = student.primary_teacher
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Add new teacher field
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='students',
                to='accounts.user',
                null=True,
                help_text='Primary teacher for this student'
            ),
        ),
        # Run data migration
        migrations.RunPython(
            migrate_teacher_data,
            reverse_code=migrations.RunPython.noop
        ),
        # Make teacher field required
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='students',
                to='accounts.user',
                help_text='Primary teacher for this student'
            ),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='student',
            name='primary_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='period2_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='temp_teacher',
        ),
        # Make account_email optional
        migrations.AlterField(
            model_name='student',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
